sudo: false
language: node_js

env: CI=true

node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - gulp ci

after_success:
  - gulp coverage

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

